name: CI

on:
  workflow_dispatch:
env:
  IMAGE_NAME: nodeapp
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: aliyun/acr-login@v1
      with:
        login-server: 'demo-registry.ap-southeast-5.cr.aliyuncs.com' 
        region-id: 'ap-southeast-5'
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
    
    - id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        docker build -t demo-registry.ap-southeast-5.cr.aliyuncs.com/sample/nodeapp:$IMAGE_TAG .
        docker push demo-registry.ap-southeast-5.cr.aliyuncs.com/sample/nodeapp:$IMAGE_TAG

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.actor }}/argocd-node-app-config
        event-type: new-image
        client-payload: '{"image": "demo-registry.ap-southeast-5.cr.aliyuncs.com/sample/nodeapp:${{ steps.commit.outputs.short }}"}'